### ISSUE TITLE
cluster-runnerが2.2.0で動かない

### ISSUE THREAD

**Issue by satoshi-kimura** [codelibs/codelibs-ja-forum#5]
ClusterHealthStatusとか、クラスがパッケージ移動していたりします。

**Comment by marevol** [comment]
SNAPSHOTを2.2にしました。
特に問題がなければ、リリースします。

**Comment by satoshi-kimura** [comment]
動かしたところ、問題なさそうです。
ありがとうございました！

**Comment by satoshi-kimura** [comment]
`
            settingsBuilder.put("script.groovy.sandbox.enabled", true);
            settingsBuilder.put("script.inline", true);
            settingsBuilder.put("script.indexed", true);
`

上記のようなコードを書いてもgroovyスクリプトが動かないんですが、
ESのディレクトリ構成が変わってるのと関係あるでしょうか？
(onじゃなくて、trueなのは2.3で試してるからですが。。)

2.2、2.3は下記のようにmodulesディレクトリができてます。
ES_HOME/modules/lang-groovy/

**Comment by marevol** [comment]
DynaRankプラグインでやったような気がするので
そちらを参考にしてみていただくのが良いかと思います。

**Comment by satoshi-kimura** [comment]
解決しました。
ありがとうございます！

groovy部分、プラグインになってたんですね。
